-- Adds 'refunded' to the project_status enum: an activity/PPA whose fund
-- transfer was returned rather than liquidated against completed work (see
-- Fund Transfer Con's Amount Refunded column and the monitoring sheet's
-- STATUS values like "Refunded"/"For refund of full amount"). Previously
-- this fell through map_status()'s substring checks (scripts/
-- seed_supabase.py) and was silently mislabeled "on_going", which is
-- misleading -- a refunded activity's funds are gone, not awaiting further
-- work. Run this against the live Supabase project (SQL Editor) before
-- re-running scripts/seed_supabase.py with the updated map_status().
--
-- NOTE: Postgres will not let a newly added enum value be USED in the same
-- transaction that added it, and the Supabase SQL Editor runs an entire
-- script as one transaction -- so running the ALTER and a verification
-- SELECT together in one execution fails with "unsafe use of new value
-- ... New enum values must be committed before they can be used", even
-- though the SELECT below doesn't reference 'refunded' by name (querying
-- the enum's full range still counts as a "use").
--
-- Run ONLY the statement below first (select just this line and execute
-- it, or run this file with the verification query commented/removed).
alter type project_status add value if not exists 'refunded';

-- Then, once that has committed, run this as a SEPARATE query execution
-- (a new query tab, or paste-and-run after the ALTER above has finished)
-- to verify:
--
--   select enum_range(null::project_status);
