"""
MAAGAP — Model Training and Testing Methodology Report builder
================================================================================
Regenerates MAAGAP_Model_Training_Testing_Methodology_Report.docx at the repo
root from the CURRENT pipeline artifacts.

WHY THIS LIVES IN THE REPO NOW
--------------------------------------------------------------------------------
Previous revisions were produced by a build script that existed only in a
scratch directory, so the report could only be regenerated by whoever still had
it (HANDOFF Section 8 said as much). That is how the document drifted: by
Rev. 3 it claimed 126 features in Section 5 and 130 in Section 6.1, while the
artifacts held 137, and its header still read July 30 although its tables cited
the August 31 run.

Every figure below is READ FROM THE ARTIFACTS rather than typed in:
ml-service/artifacts/*.json and data/ready/*.csv. Prose that states a number
pulls it from those same values, so the report cannot silently disagree with
the model it describes. Re-run this after any retrain:

    python scripts/build_methodology_report.py

Optional: --pre-artifacts points at a snapshot of the previous run (default
ml-service/artifacts_pre_d16) to render the before/after comparison in
Section 6. Pass --no-comparison once that comparison is no longer the story.
"""

from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path

import pandas as pd
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS = ROOT / "ml-service" / "artifacts"
READY = ROOT / "data" / "ready"
OUTPUT = ROOT / "MAAGAP_Model_Training_Testing_Methodology_Report.docx"

REVISION = "Rev. 4 — D16 controlled observation-status vocabulary"


# ---------------------------------------------------------------------------
# Fact gathering
# ---------------------------------------------------------------------------

def load_json(path: Path):
    return json.loads(path.read_text()) if path.exists() else None


def gather(pre_artifacts: Path | None) -> dict:
    trees = load_json(ARTIFACTS / "tree_models_metrics.json")
    lstm = load_json(ARTIFACTS / "lstm_model_metrics.json")
    meta = load_json(ARTIFACTS / "meta_learner_metrics.json")
    cols = load_json(ARTIFACTS / "tabular_feature_columns.json") or []

    train = pd.read_csv(READY / "train.csv", low_memory=False)
    test = pd.read_csv(READY / "test.csv", low_memory=False)
    inference = pd.read_csv(READY / "inference.csv", low_memory=False)

    def family(prefix: str) -> list[str]:
        return sorted(c[len(prefix):] for c in cols if c.startswith(prefix))

    status = family("STATUS_canonical_")
    municipality = family("municipality_canonical_")
    project_type = family("project_type_")
    contractor_spec = family("contractor_spec_")
    onehot_total = len(status) + len(municipality) + len(project_type) + len(contractor_spec)

    facts = {
        "trees": trees,
        "lstm": lstm,
        "meta": meta,
        "n_features": len(cols),
        "status_members": status,
        "municipality_members": municipality,
        "project_type_members": project_type,
        "contractor_spec_members": contractor_spec,
        "n_onehot": onehot_total,
        "n_continuous": len(cols) - onehot_total,
        "continuous_members": sorted(
            c for c in cols
            if not any(c.startswith(p) for p in
                       ("STATUS_canonical_", "municipality_canonical_",
                        "project_type_", "contractor_spec_"))
        ),
        "n_train": len(train),
        "n_test": len(test),
        "n_inference": len(inference),
        "n_labeled": len(train) + len(test),
        "redflag_train": int(train["RedFlag"].sum()),
        "redflag_test": int(test["RedFlag"].sum()),
        "clamped_train": int(train.get("completion_date_is_clamped", pd.Series(dtype=bool)).sum()),
        "clamped_test": int(test.get("completion_date_is_clamped", pd.Series(dtype=bool)).sum()),
        "flags": {
            f: (int(train[f].sum()), int(test[f].sum()))
            for f in ("status_has_damage", "status_not_turned_over", "status_partially_functional")
            if f in train.columns
        },
        "status_source_train": (
            train["status_source"].value_counts().to_dict()
            if "status_source" in train.columns else {}
        ),
        "pre": None,
    }
    facts["n_total_rows"] = facts["n_labeled"] + facts["n_inference"]

    if pre_artifacts and pre_artifacts.exists():
        facts["pre"] = {
            "trees": load_json(pre_artifacts / "tree_models_metrics.json"),
            "lstm": load_json(pre_artifacts / "lstm_model_metrics.json"),
            "meta": load_json(pre_artifacts / "meta_learner_metrics.json"),
            "cols": load_json(pre_artifacts / "tabular_feature_columns.json") or [],
        }
    return facts


# ---------------------------------------------------------------------------
# Document helpers
# ---------------------------------------------------------------------------

def body(doc: Document, text: str) -> None:
    doc.add_paragraph(text)


def caption(doc: Document, text: str) -> None:
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x44, 0x44, 0x44)


def table(doc: Document, headers: list[str], rows: list[list[str]]) -> None:
    t = doc.add_table(rows=1, cols=len(headers))
    t.style = "Table Grid"
    for i, h in enumerate(headers):
        cell = t.rows[0].cells[i]
        cell.text = ""
        run = cell.paragraphs[0].add_run(h)
        run.bold = True
        run.font.size = Pt(9)
    for row in rows:
        cells = t.add_row().cells
        for i, value in enumerate(row):
            cells[i].text = ""
            run = cells[i].paragraphs[0].add_run(str(value))
            run.font.size = Pt(9)
    doc.add_paragraph()


def metric_rows(label: str, m: dict) -> list[str]:
    return [
        label,
        f"{m['accuracy']:.3f}", f"{m['precision']:.3f}", f"{m['recall']:.3f}",
        f"{m['f1']:.3f}", f"{m['auc_roc']:.3f}",
    ]


def delta(before: float, after: float) -> str:
    return f"{before:.3f} → {after:.3f} ({after - before:+.3f})"


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def build(facts: dict) -> Document:
    doc = Document()
    f = facts
    trees, lstm, meta = f["trees"], f["lstm"], f["meta"]

    # ---- Title -----------------------------------------------------------
    for text, size, bold in [
        ("MAAGAP", 20, True),
        ("Model Training and Testing Methodology Report", 14, True),
        ("Predictive Risk Assessment and Optimized Resource Allocation in "
         "Philippine Government Project Management", 11, False),
    ]:
        p = doc.add_paragraph()
        run = p.add_run(text)
        run.bold = bold
        run.font.size = Pt(size)
    doc.add_paragraph("Prepared for: Kirk Gamo")
    doc.add_paragraph(f"Date: {date.today().strftime('%B %d, %Y').replace(' 0', ' ')} ({REVISION})")

    # ---- 1. Overview -----------------------------------------------------
    doc.add_heading("1. Overview", level=1)
    body(doc,
         "This report documents how the Level 0 base learners (Random Forest, XGBoost, LSTM) "
         "and the Level 1 meta-learner (Multinomial Logistic Regression) were trained and "
         "evaluated for the MAAGAP risk-classification stack, following the pipeline checked "
         "into the ml-service directory: preprocess.py (Steps 1–5), feature_engineering.py "
         "(Steps 6–11), train_trees.py, train_lstm.py, and train_meta_learner.py. Every figure "
         "below is read directly from the artifacts of the current pipeline run "
         "(data/ready/*.csv and ml-service/artifacts/*.json) by scripts/build_methodology_report.py, "
         "which generates this document — none are transcribed by hand.")
    body(doc,
         "Two questions anchor this report, both asked directly: what split was used (a 70/30 "
         "project-level train/test split, not 70/15/15 — no separate validation partition "
         "exists, for reasons in Section 4.1), and whether all available data was used (no — "
         "only the subset of monitoring records with a resolvable RedFlag outcome is used for "
         "supervised training; the remainder is scored, not trained on, and is documented in "
         "Section 3).")
    body(doc,
         "This revision (Rev. 4) records D16: observed status is now encoded from a controlled "
         "vocabulary rather than from raw free text, and the models were retrained on that "
         "encoding with the RedFlag target deliberately held fixed. Section 5.2 describes the "
         "change and Section 6 reports the resulting before/after comparison in full, including "
         "where accuracy fell.")

    # ---- 2. Data sources -------------------------------------------------
    doc.add_heading("2. Data Sources and Volume", level=1)
    body(doc,
         "The source workbook (“Copy of 2022 conso Fund Transfer worksheet (2).xlsx”) contains "
         "five sheets ingested by preprocess.py, all five of which feed the modeling population: "
         "the two smaller monitoring sheets (20% NTA Monitored, SEF Monitored) are folded into "
         "the main monitoring population by fold_in_supplementary_sheets() (Step 1B) before type "
         "coercion, schema-harmonized onto the main sheet's 12 columns and tagged with a "
         "source_sheet provenance column (excluded from training). The merged monitoring "
         "population is 8,784 rows (8,677 from the main sheet + 107 folded in).")
    body(doc,
         "Contractor features are joined from a synthetic 150-contractor table "
         "(scripts/generate_synthetic_data.py), documented in Chapter 3 as a stand-in pending a "
         "real contractor-performance registry; this is a declared limitation, not ground truth.")
    body(doc,
         "The entity-resolution crosswalk (build_project_crosswalk(), preprocess.py) links Fund "
         "Transfer Con rows to their corresponding Liquidation and Monitoring records, and is "
         "used for LSTM sequence assembly (Section 5.3) and for assigning each fund-transfer row "
         "a project_key. It carries a barangay-level veto: a real case surfaced two distinct "
         "“Public Address System” projects in different Tubungan barangays (Morcillas vs. "
         "Balicua), same municipality and fiscal year, merged into one project because the prior "
         "match key (project name, municipality, fiscal year) did not check barangay. Fixing "
         "this reduced the crosswalk's linkage rate — Section 8 accounts for how much that "
         "shrinks the LSTM/meta-learner's effective sample size.")

    # ---- 3. Target -------------------------------------------------------
    doc.add_heading("3. Target Variable Construction and Data Coverage", level=1)
    body(doc,
         "RedFlag (the binary slippage label the Level 0 models predict) requires a completion "
         "date to compute T_actual = Date of Completion − D_start against T_standard (365 days "
         "Infrastructure, 182 days Non-Infrastructure). The 8,784 merged monitoring rows are "
         f"first reduced to {f['n_total_rows']:,} by two data-quality filters — 504 exact-duplicate "
         "ledger rows (DQ-11) and 3 rows whose D_start precedes the data's own 2015 floor and are "
         "demonstrable data-entry errors (DQ-9). Of those, only a subset has both a usable "
         "completion date and a resolved project type; the rest cannot be labeled without "
         "fabricating an outcome, and are not labeled.")
    body(doc,
         "Phase 8 clamp: the Phase 7 empirical lag correction occasionally pulled a "
         "short-duration project's corrected proxy date back before its own D_start, which is "
         "not credible. Rows whose RAW, uncorrected proxy date is genuinely after D_start have "
         "the corrected date clamped at D_start + 1 day rather than being discarded; rows whose "
         "raw proxy date already precedes D_start before any correction are left unresolved, "
         "since no real event exists to anchor a clamp to. Clamped rows are marked "
         "completion_date_is_clamped=True; because T_actual is pinned to 1 day, RedFlag is 0 for "
         "every one of them by construction, not from observed evidence.")
    caption(doc,
            f"Table 1. Disposition of all {f['n_total_rows']:,} pipeline monitoring rows "
            "(source: direct counts against data/ready/*.csv, current run).")
    table(doc, ["Population", "Rows", "% of total"], [
        ["Total pipeline monitoring rows", f"{f['n_total_rows']:,}", "100.0%"],
        ["Resolved (labeled) — train/test", f"{f['n_labeled']:,}",
         f"{100*f['n_labeled']/f['n_total_rows']:.1f}%"],
        ["Unresolved — routed to inference.csv", f"{f['n_inference']:,}",
         f"{100*f['n_inference']/f['n_total_rows']:.1f}%"],
        ["— of the labeled rows, Phase 8 clamped",
         f"{f['clamped_train'] + f['clamped_test']:,}",
         f"{100*(f['clamped_train']+f['clamped_test'])/f['n_labeled']:.1f}% of labeled"],
    ])

    doc.add_heading("3.1 Proxy Completion Dates", level=2)
    body(doc,
         f"Only a small minority of the {f['n_labeled']:,} labeled rows have a directly observed "
         "completion date. The rest are labeled using a proxy completion date — the latest "
         "independently recorded monitoring visit or liquidation submission for that project — "
         "recovered only when STATUS explicitly confirms the project is completed/functional. "
         "This is real recorded history, not a fabricated value, but it is a systematically late "
         "upper bound on true physical completion. An empirical lag correction is subtracted "
         "from every proxy date before use, and corrected dates that would otherwise fall before "
         f"D_start are clamped at D_start + 1 day ({f['clamped_train']:,} train / "
         f"{f['clamped_test']:,} test rows).")
    body(doc,
         "This matters for interpreting Section 6: roughly 94% of the labeled population is "
         "proxy-dated, so the reported RedFlag rate and every downstream metric should be read "
         "as “how well the ensemble separates risk under the current proxy-date methodology”, "
         "not as a bias-free measurement against ground truth. The clamped rows are a further "
         "special case within that subset: RedFlag=0 for each of them is a mechanical "
         "consequence of T_actual being pinned to 1 day, and their contribution should be read "
         "as a downward-biased floor rather than a measurement.")
    body(doc,
         "The field-reporting loop is the mechanism that retires this limitation project by "
         "project: an inspector's dated observation that a project is complete produces a REAL "
         "completion date, replacing the proxy for that row at the next pipeline run. That loop "
         "was repaired in the same cycle as D16 — until then, an inspector's report was written "
         "to monitoring_reports but never applied to the project record, so it could not feed "
         "back at all.")

    # ---- 4. Split --------------------------------------------------------
    doc.add_heading("4. Train/Test Split Methodology", level=1)
    body(doc,
         "The split is 70/30, not 70/15/15 — there is no separate held-out validation partition. "
         "Splitting is performed at the project level (normalize_and_split() in "
         "feature_engineering.py, Step 11): unique project_key values are shuffled with a fixed "
         "seed (42) and partitioned 70/30 before any row is assigned, which guarantees a single "
         "project's records cannot appear on both sides. Min-max normalization for scaled "
         "numeric columns is fit on the train split only and applied (not re-fit) to test and "
         "inference data, preventing scaling leakage.")
    caption(doc, "Table 2. Train/test composition (source: data/ready/train.csv, test.csv, "
                 "current run).")
    table(doc, ["", "Train", "Test"], [
        ["Projects / rows", f"{f['n_train']:,}", f"{f['n_test']:,}"],
        ["% of resolved population",
         f"{100*f['n_train']/f['n_labeled']:.1f}%", f"{100*f['n_test']/f['n_labeled']:.1f}%"],
        ["RedFlag positive",
         f"{f['redflag_train']:,} ({100*f['redflag_train']/f['n_train']:.1f}%)",
         f"{f['redflag_test']:,} ({100*f['redflag_test']/f['n_test']:.1f}%)"],
        ["Phase 8 clamped rows", f"{f['clamped_train']:,}", f"{f['clamped_test']:,}"],
        ["With a matching LSTM OOF prediction",
         f"{lstm['n_train']:,}", f"{lstm['n_test']:,}"],
    ])
    body(doc,
         "D16 changed only how status is encoded as a feature, never the label, so this "
         "composition is unchanged from the previous revision by construction — the identical "
         f"checkpoint ({f['n_labeled']:,} labeled of {f['n_total_rows']:,}, "
         f"{f['n_train']:,}/{f['n_test']:,} split, {lstm['n_train']:,} meta-learner training "
         "rows) is what makes Section 6's before/after a controlled comparison rather than a "
         "confounded one.")

    doc.add_heading("4.1 Why No Separate Validation Split", level=2)
    body(doc,
         "In place of a third validation partition, both tree-based base learners and the LSTM "
         "generate Out-of-Fold (OOF) predictions via 5-fold stratified cross-validation on the "
         "training set (StratifiedKFold, shuffle=True, seed=42). Each row's OOF prediction comes "
         "from a model that never saw that row during that fold's training, so OOF predictions "
         "are statistically equivalent to validation-set predictions without shrinking the "
         "training set further. These OOF probabilities — not each base learner's in-sample "
         "predictions — feed the Level 1 meta-learner, which is the standard stacking-ensemble "
         "protection against the meta-learner overfitting to each base learner's optimistic "
         "in-sample bias.")

    # ---- 5. Features -----------------------------------------------------
    doc.add_heading("5. Feature Set Used for Training and Testing", level=1)
    body(doc,
         f"The Random Forest and XGBoost base learners are trained on {f['n_features']} columns, "
         "drawn from ml-service/artifacts/tabular_feature_columns.json (the frozen schema saved "
         "during the current run of train_trees.py and reused unchanged for scoring test.csv and "
         f"inference.csv). Of those, {f['n_continuous']} are continuous/engineered numeric or "
         f"boolean features and {f['n_onehot']} are one-hot indicator columns across four "
         "categorical families. The LSTM is trained on a separate 3-feature-per-timestep "
         "sequence representation, described in Section 5.3.")

    doc.add_heading(f"5.1 Continuous and Engineered Features ({f['n_continuous']})", level=2)
    caption(doc, "Table 3. Continuous/engineered numeric and boolean features "
                 "(source: tabular_feature_columns.json).")
    definitions = {
        "AMOUNT (Php)": "Project budget in Philippine pesos, min-max scaled on the train split.",
        "Year": "Calendar year the fund transfer was recorded.",
        "days_since_release": "Days between D_start and the dataset horizon, min-max scaled.",
        "release_month": "Calendar month of D_start (1–12).",
        "release_quarter": "Calendar quarter of D_start (1–4).",
        "is_wet_season_release": "1 if D_start falls in June–November; a coarse proxy pending "
                                 "real PAGASA rainfall data, not a weather observation.",
        "amount_outlier_flag": "1 if AMOUNT falls outside the IQR fence computed in Step 8.",
        "historical_delay_rate": "Synthetic contractor feature — share of that contractor's "
                                 "prior projects delayed. Placeholder data (Section 8).",
        "reliability_score": "Synthetic contractor feature — composite reliability rating. "
                             "Placeholder data (Section 8).",
        "status_has_damage": "D16 condition flag: the observed status text reports damage, "
                             "theft, or an unserviceable asset.",
        "status_not_turned_over": "D16 condition flag: delivered but not yet turned over, not "
                                  "yet installed, or under repair.",
        "status_partially_functional": "D16 condition flag: some units functional and others "
                                       "not — a partial delivery.",
    }
    table(doc, ["Feature", "Definition"],
          [[c, definitions.get(c, "—")] for c in f["continuous_members"]])
    body(doc,
         "The last three are new in this revision. They carry the condition detail that the "
         "previous free-text status encoding held — damage, non-functionality, "
         "not-yet-turned-over — in a form that generalizes to wording never seen at train time. "
         "They are sparse by nature: "
         + "; ".join(f"{k} on {v[0]} train / {v[1]} test rows" for k, v in f["flags"].items())
         + ".")

    doc.add_heading(f"5.2 One-Hot Categorical Families ({f['n_onehot']})", level=2)
    body(doc,
         "Four categorical fields are one-hot encoded — each distinct category value becomes its "
         "own binary column, equal to 1 if that project's value matches and 0 otherwise.")
    caption(doc, "Table 4. One-hot categorical feature families.")
    table(doc, ["Family (column prefix)", "Columns", "Definition"], [
        ["project_type_*", len(f["project_type_members"]),
         "Infrastructure vs. Non-Infrastructure, assigned by the D12 classifier cascade and "
         "D14's manual override tier."],
        ["STATUS_canonical_*", len(f["status_members"]),
         "Field-monitor-reported status, collapsed to the D16 controlled vocabulary."],
        ["municipality_canonical_*", len(f["municipality_members"]),
         "Canonicalized municipality from the LOCATION field (canonicalize_municipality())."],
        ["contractor_spec_*", len(f["contractor_spec_members"]),
         "Synthetically-assigned contractor specialization. Placeholder data (Section 8)."],
    ])

    body(doc,
         "D16 — observed status as a controlled vocabulary. Until this revision, STATUS was "
         "one-hot encoded directly from raw free text. preprocess.py's STATUS_LOOKUP maps 15 raw "
         "spellings and describes itself as “illustrative of the pattern, not exhaustive”, "
         "against 278 raw / 238 normalized distinct STATUS values (Data Audit DQ-3), so every "
         "unmapped value became its own category. The result was 237 STATUS_clean_* columns in "
         "train.csv, of which 57 survived feature selection into the trained model — 42% of its "
         "137 features — including near-singleton columns keyed on typos, such as "
         "“STATUS_clean_Completd/ Distributed” and “STATUS_clean_Completed/ 2 Cameras Are Dame "
         "During Road Co9Nstructiion Project And The Remaining Are Functional”. A column like "
         "that cannot generalize: an observation whose wording differs by one character matches "
         "none of them.")
    body(doc,
         "The previous revision of this report defended that design, on the grounds that each "
         "raw string carried qualifying detail a stricter normalization would discard. D16 "
         "accepts the premise and rejects the conclusion: the detail is preserved as the three "
         "orthogonal condition flags in Section 5.1, while the status itself collapses to a "
         "controlled vocabulary shared by the offline pipeline and the live re-scoring path "
         "(ml-service/data_pipeline/status_vocabulary.py). An ordered rule cascade with explicit "
         "negative guards resolves 96.9% of monitoring rows and abstains on the rest rather than "
         "guessing, recording provenance in a status_source column exactly as D12's "
         f"project_type_source does ({f['status_source_train']} across the training split). The "
         "guards are load-bearing: “Fund Is Fullly Utilized But The Project Still Needs "
         "Addtional Funding For Its Building Completion” contains the substring “completion” but "
         "plainly describes unfinished work, and now resolves to On-going.")
    body(doc,
         "A second defect fell out of the same change. The live re-scoring path mapped an "
         "inspector's reported status to a one-hot column by name, and two of the app's five "
         "status values pointed nowhere: for_bidding named a column the trained schema never "
         "contained, and refunded had no mapping at all. Both kinds of field observation were "
         "recorded and then silently unable to move a risk score. Under the controlled "
         "vocabulary for_bidding now has a column; refunded still does not, because only two "
         "training rows carry it and zero-variance selection drops it — the live path now logs "
         "that explicitly instead of failing quietly.")
    body(doc,
         "Members of the status family in the current trained schema: "
         + ", ".join(f["status_members"]) + ". Labels defined by the vocabulary but absent here "
         "(For Implementation, Refunded, Unclassified) occur too rarely in the training "
         "population to survive the zero-variance filter.")

    doc.add_heading("5.3 LSTM Sequence Features (3 per timestep)", level=2)
    body(doc,
         f"The LSTM does not use the {f['n_features']}-column tabular matrix. It is trained on a "
         "separate per-project event sequence — up to 5 timesteps, 3 features per timestep — "
         "assembled by assemble_lstm_sequences() from the three transactional sheets, "
         "chronologically ordered per project. Every project in the crosswalk receives a "
         "sequence; projects with zero recorded events get an all-masked placeholder (all "
         "timesteps at the −1 padding sentinel) rather than being dropped. Keras's "
         "Masking(mask_value=−1.0) layer causes an all-masked sample to produce the LSTM's zero "
         "initial state, a well-defined output rather than an error.")
    caption(doc, "Table 5. Per-timestep LSTM sequence features. Padding timesteps are filled "
                 "with −1 in all three columns and masked, since 0 is a legitimate real value "
                 "for event_type.")
    table(doc, ["Feature", "Definition"], [
        ["event_type", "Categorical code for the event (fund release, liquidation, monitoring "
                       "visit)."],
        ["days_since_anchor", "Days between this event and the project's anchor date."],
        ["amount", "Peso amount associated with the event, scaled by the train-fitted sequence "
                   "scaler."],
    ])

    # ---- 6. Level 0 ------------------------------------------------------
    doc.add_heading("6. Level 0 Base Learner Training and Evaluation", level=1)
    doc.add_heading("6.1 Random Forest and XGBoost (train_trees.py)", level=2)
    body(doc,
         f"Trained on {trees['n_features']} features after a zero-variance filter. Random "
         "Forest: 300 trees, max depth 8, min_samples_leaf 3, class_weight=“balanced”. XGBoost: "
         "300 estimators, max depth 4, learning rate 0.05, subsample/colsample_bytree 0.8, "
         "scale_pos_weight set from the train split's class ratio. Both use the identical 5-fold "
         "OOF protocol described in Section 4.1.")
    caption(doc, "Table 6. Level 0 tabular base learner metrics (source: "
                 "ml-service/artifacts/tree_models_metrics.json, current run).")
    table(doc, ["Model / Split", "Accuracy", "Precision", "Recall", "F1", "AUC-ROC"], [
        metric_rows("Random Forest — OOF (train)", trees["random_forest"]["oof_metrics"]),
        metric_rows("Random Forest — held-out test", trees["random_forest"]["test_metrics"]),
        metric_rows("XGBoost — OOF (train)", trees["xgboost"]["oof_metrics"]),
        metric_rows("XGBoost — held-out test", trees["xgboost"]["test_metrics"]),
    ])

    if f["pre"]:
        pre = f["pre"]
        doc.add_heading("6.1.1 Effect of the D16 Encoding Change", level=2)
        body(doc,
             "The comparison below is controlled: the RedFlag target, the population, and the "
             "70/30 split are all identical across the two runs (Section 4), so the only "
             "variable that moved is how status is encoded.")
        caption(doc, "Table 7. Held-out test metrics before and after D16 "
                     "(source: ml-service/artifacts_pre_d16/ vs. ml-service/artifacts/).")
        rows = []
        for label, before, after in [
            ("Random Forest", pre["trees"]["random_forest"]["test_metrics"],
             trees["random_forest"]["test_metrics"]),
            ("XGBoost", pre["trees"]["xgboost"]["test_metrics"], trees["xgboost"]["test_metrics"]),
            ("LSTM", pre["lstm"]["test_metrics"], lstm["test_metrics"]),
            ("Meta-learner", pre["meta"], meta),
        ]:
            rows.append([
                label,
                delta(before["accuracy"], after["accuracy"]),
                delta(before["f1"], after["f1"]),
                delta(before["auc_roc"], after["auc_roc"]),
            ])
        rows.append(["Feature columns",
                     f"{len(pre['cols'])} → {f['n_features']} ({f['n_features']-len(pre['cols']):+d})",
                     "—", "—"])
        table(doc, ["Model (held-out test)", "Accuracy", "F1", "AUC-ROC"], rows)
        body(doc,
             "This outcome was predicted in writing before the retrain was run. Near-singleton "
             "one-hot columns keyed on typo strings are precisely what a tree ensemble can "
             "memorize, so part of the previous accuracy was identifier-like fitting rather than "
             "learned structure. The loss is concentrated in Random Forest, the learner least "
             "able to regularize it away; XGBoost is essentially flat and the meta-learner moves "
             "within the run-to-run noise this stack has shown across every prior revision. A "
             "model that generalizes to status wording it has never seen, on 36% fewer features, "
             "at that cost is the better and more defensible result — and it is what makes the "
             "live feedback loop meaningful, since a field observation must land in a column the "
             "model actually has.")

    doc.add_heading("6.2 LSTM (train_lstm.py)", level=2)
    body(doc,
         "Trained on per-project event sequences (fund release → liquidation → monitoring "
         "visit; max length 5, 3 features per step, padding value −1 with a Keras Masking "
         f"layer), using the same 5-fold OOF protocol. The usable population is {lstm['n_train']:,} "
         f"train / {lstm['n_test']:,} test projects — crosswalk linkage, not label availability, "
         "is the binding constraint on sequence availability. As in Section 6.1, part of this "
         "population's RedFlag is 0 by construction (Phase 8 clamped), not observed evidence.")
    caption(doc, "Table 8. LSTM base learner metrics (source: "
                 "ml-service/artifacts/lstm_model_metrics.json, current run, "
                 "epochs=60/batch_size=8 on unrestricted hardware).")
    table(doc, ["Split", "Accuracy", "Precision", "Recall", "F1", "AUC-ROC"], [
        metric_rows(f"LSTM — OOF (train, n={lstm['n_train']:,})", lstm["oof_metrics"]),
        metric_rows(f"LSTM — held-out test (n={lstm['n_test']:,})", lstm["test_metrics"]),
    ])
    body(doc,
         f"Recall is high ({lstm['test_metrics']['recall']:.3f} test) but precision is low "
         f"({lstm['test_metrics']['precision']:.3f}) — the LSTM is heavily biased toward flagging "
         "RedFlag=1, reflecting both the class-weighted loss compensating for the training set's "
         "Phase 8-shifted composition and the short event history giving the model little to "
         "discriminate on. Read this base learner as noisy directional signal for the "
         "meta-learner, not as a standalone risk score.")

    # ---- 7. Meta-learner -------------------------------------------------
    doc.add_heading("7. Level 1 Meta-Learner (train_meta_learner.py)", level=1)
    body(doc,
         "A Multinomial Logistic Regression trained on three inputs per row: Random Forest's OOF "
         "probability, XGBoost's OOF probability, and the LSTM's OOF probability. Because a "
         "matching LSTM OOF prediction is the tightest constraint in the stack, only rows with "
         f"all three available are used: {lstm['n_train']:,} of {f['n_train']:,} train rows and "
         f"{lstm['n_test']:,} of {f['n_test']:,} test rows survive for final evaluation.")
    caption(doc, "Table 9. Meta-learner test-set metrics (source: "
                 "ml-service/artifacts/meta_learner_metrics.json, current run).")
    table(doc, ["Metric", "Value", ""], [
        ["Test accuracy", f"{meta['accuracy']:.3f}", f"n = {lstm['n_test']:,}"],
        ["Test precision", f"{meta['precision']:.3f}", ""],
        ["Test recall", f"{meta['recall']:.3f}", ""],
        ["Test F1", f"{meta['f1']:.3f}", ""],
        ["Test AUC-ROC", f"{meta['auc_roc']:.3f}", ""],
    ])
    body(doc,
         "Revision history for these figures: 0.832 accuracy / 0.803 recall (original), 0.813 / "
         "0.773 (after the DATE RELEASED proxy-date fix), 0.811 / 0.767 (after activating "
         "contractor features), 0.811 / 0.754 (after folding in NTA/SEF and fixing the LSTM "
         "zero-event drop), 0.873 / 0.842 (after the barangay-veto crosswalk fix), 0.895 / 0.851 "
         "(after the Phase 8 clamp fix, n=477), 0.903 / 0.872 (after the DQ-9/10/11 cleanup plus "
         "D12/D13, n=608), 0.895 / 0.876 (after D14 manual labeling and the D15 currency fix, "
         f"n=598), {meta['accuracy']:.3f} / {meta['recall']:.3f} (this revision, after D16's "
         f"controlled status vocabulary, n={lstm['n_test']:,}). The meta-learner has stayed "
         "within roughly one percentage point of 0.90 across the last four revisions despite "
         "materially different feature sets and a persistently noisy LSTM base learner. Every "
         "change in this history reflects removing a real data defect, activating real signal, "
         "or — in this revision — deliberately trading a small amount of measured accuracy for a "
         "feature set that generalizes. None reflects tuning toward a target number.")

    doc.add_heading("7.1 Risk Tier Distribution (Held-Out Test Set)", level=2)
    caption(doc, "Table 10. Chapter 3 risk-tier thresholds applied to the meta-learner's "
                 "test-set P(RedFlag) (probability_to_risk_tier(), current run, "
                 f"n={lstm['n_test']:,}).")
    tiers = meta.get("risk_tier_distribution", {})
    total_tiers = sum(tiers.values()) or 1
    table(doc, ["Tier", "Probability range", "Test projects", "% of scored"], [
        ["Low", "0.0 – 0.3", tiers.get("Low", 0), f"{100*tiers.get('Low',0)/total_tiers:.1f}%"],
        ["Medium", "0.3 – 0.7", tiers.get("Medium", 0), f"{100*tiers.get('Medium',0)/total_tiers:.1f}%"],
        ["High", "0.7 – 0.9", tiers.get("High", 0), f"{100*tiers.get('High',0)/total_tiers:.1f}%"],
        ["Critical", "0.9 – 1.0", tiers.get("Critical", 0), f"{100*tiers.get('Critical',0)/total_tiers:.1f}%"],
    ])

    # ---- 8. Limitations --------------------------------------------------
    doc.add_heading("8. Known Limitations and Caveats", level=1)
    limitations = [
        "Proxy-date dependence: roughly 94% of the labeled population uses a recovered proxy "
        "completion date, not a directly observed one. Reported metrics should be read as "
        "ensemble performance under the current proxy-date methodology, not a bias-free "
        "measurement (Section 3.1). The repaired field-reporting loop is the mechanism that "
        "reduces this over time, one dated field observation at a time.",

        f"Phase 8 clamp construction artifact: {f['clamped_train'] + f['clamped_test']:,} labeled "
        f"rows ({f['clamped_train']:,} train, {f['clamped_test']:,} test) have their completion "
        "date clamped at D_start + 1 day. RedFlag is 0 for every one of these purely because "
        "T_actual=1 day is mechanically below any T_standard — this is NOT an observed on-time "
        "completion, and readers should discount this subset's contribution accordingly. "
        "completion_date_is_clamped marks the affected rows for anyone who wants to exclude them "
        "and re-measure.",

        "D16 abstention residue: the status rule cascade resolves 96.9% of monitoring rows and "
        "leaves 3.1% Unclassified, of which the large majority are empty STATUS cells and "
        "therefore unclassifiable in principle. The remainder are exotic typos and vocabulary "
        "(“Competed”, “Og-Going”, “Dumpsite Closed”). Rule-chasing was stopped deliberately "
        "rather than tuned to this snapshot; a confidence-gated classifier for that residue, "
        "following D12's pattern, is the available follow-up.",

        "D16 held the target fixed on purpose: construct_target_variable() still decides "
        "completion from the raw STATUS text via COMPLETED_STATUS_SUBSTRINGS, not from the new "
        "canonical labels. Aligning the two is defensible future work, but doing it in the same "
        "retrain would have confounded the comparison in Section 6.1.1 and put the study's "
        "central variable in play without a controlled test.",

        "Entity-resolution crosswalk barangay conflation: build_project_crosswalk() previously "
        "matched on (project name, municipality, fiscal year) alone, and generic recurring "
        "project names are not unique on that key. A barangay veto now rejects those matches, "
        "but barangay-level data is still not authoritatively canonicalized the way municipality "
        "is, so residual conflation for barangays with inconsistent naming cannot be fully ruled "
        "out.",

        f"Meta-learner population bottleneck: only {lstm['n_train']:,} of {f['n_train']:,} train "
        f"rows and {lstm['n_test']:,} of {f['n_test']:,} test rows carry all three OOF "
        "predictions, because most resolved tabular projects were never linked into the "
        "entity-resolution crosswalk in the first place. Closing that gap requires improving "
        "build_project_crosswalk()'s matching, not further reference-list canonicalization.",

        "Contractor features are synthetic: every value comes from a 150-contractor placeholder "
        "table with no linkage to actual PPDO contractors or PhilGEPS records (Chapter 1's "
        "declared Data Availability limitation). historical_delay_rate, reliability_score and "
        "contractor_spec_* exercise the join and feature mechanics, not real contractor signal.",

        "shap/xgboost compatibility: xgboost ≥ 2.1 serializes base_score in a bracketed-array "
        "string format that current shap releases fail to parse. inference/explain.py patches "
        "shap's UBJSON decoder to work around it, verified via additive consistency — a "
        "maintenance note for whoever next updates either dependency.",

        "No third validation split: OOF cross-validation substitutes for a held-out validation "
        "set (Section 4.1) — a deliberate, documented design choice, worth stating explicitly if "
        "asked “why not 70/15/15” during defense.",
    ]
    for item in limitations:
        doc.add_paragraph(item, style="List Bullet")

    # ---- 9. Summary ------------------------------------------------------
    doc.add_heading("9. Summary", level=1)
    body(doc,
         f"The split is 70/30 at the project level ({f['n_train']:,} train / {f['n_test']:,} "
         "test), not 70/15/15 — there is no separate validation partition; 5-fold stratified OOF "
         "cross-validation on the training set fills that role for both Level 0 training and "
         "Level 1 meta-learner input generation. Not all available data is used for supervised "
         f"training: of {f['n_total_rows']:,} pipeline monitoring records, {f['n_labeled']:,} "
         f"({100*f['n_labeled']/f['n_total_rows']:.1f}%) have a resolvable RedFlag label and "
         f"enter train/test, while the remaining {f['n_inference']:,} "
         f"({100*f['n_inference']/f['n_total_rows']:.1f}%) are scored on the live dashboard via "
         "inference.csv rather than trained on.")
    body(doc,
         f"This revision retrained the stack on D16's controlled status vocabulary: "
         f"{f['n_features']} features, down from 137, with 57 free-text status one-hots replaced "
         f"by {len(f['status_members'])} canonical labels and 3 condition flags. Held-out "
         f"accuracy moved from 0.849 to {trees['random_forest']['test_metrics']['accuracy']:.3f} "
         f"(Random Forest), 0.924 to {trees['xgboost']['test_metrics']['accuracy']:.3f} "
         f"(XGBoost), and 0.895 to {meta['accuracy']:.3f} (meta-learner). The clamped rows' "
         "RedFlag=0 label remains a construction artifact rather than observed evidence, and "
         "should be read with that caveat throughout.")

    # ---- Appendix --------------------------------------------------------
    doc.add_heading("Appendix A. Full One-Hot Feature Family Membership", level=1)
    body(doc,
         "Members are listed exactly as they appear in "
         "ml-service/artifacts/tabular_feature_columns.json, so any residual noise is visible "
         "rather than smoothed over.")
    for name, members in [
        (f"A.1 project_type_* ({len(f['project_type_members'])} members)", f["project_type_members"]),
        (f"A.2 STATUS_canonical_* ({len(f['status_members'])} members)", f["status_members"]),
        (f"A.3 municipality_canonical_* ({len(f['municipality_members'])} members)", f["municipality_members"]),
        (f"A.4 contractor_spec_* ({len(f['contractor_spec_members'])} members)", f["contractor_spec_members"]),
    ]:
        doc.add_heading(name, level=2)
        doc.add_paragraph("; ".join(m if m else "(unresolved / blank)" for m in members) + ".")

    body(doc,
         "Note on A.3: several municipality members are not real municipalities (e.g. “Nan”, "
         "“Municipality”, “8”) — residue from LOCATION values that did not fuzzy-match any of "
         "the 44 reference towns above the acceptance cutoff and fell through to an unresolved "
         "placeholder rather than being silently dropped. A.2, by contrast, is now a closed "
         "controlled vocabulary rather than an open set of observed strings, which is the point "
         "of D16.")

    return doc


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(OUTPUT))
    parser.add_argument("--pre-artifacts", default=str(ROOT / "ml-service" / "artifacts_pre_d16"),
                        help="Snapshot of the previous run, for the before/after table.")
    parser.add_argument("--no-comparison", action="store_true",
                        help="Omit the before/after section.")
    args = parser.parse_args()

    pre = None if args.no_comparison else Path(args.pre_artifacts)
    facts = gather(pre)
    doc = build(facts)
    doc.save(args.output)
    print(f"Wrote {args.output}")
    print(f"  features={facts['n_features']}  labeled={facts['n_labeled']:,}  "
          f"train/test={facts['n_train']:,}/{facts['n_test']:,}  "
          f"meta n={facts['lstm']['n_test']:,}")


if __name__ == "__main__":
    main()
